name: canokey_console
description: Manage your CanoKey via NFC or USB.
publish_to: 'none'

version: 1.0.2+0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: 3.24.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  url_launcher: ^6.3.1
  file_picker: 8.1.7
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  flutter_nfc_kit: ^3.6.0-rc.6
  base32: ^2.1.3
  convert: ^3.1.2
  percent_indicator: ^4.2.4
  timer_controller: ^1.0.0
  loader_overlay: ^4.0.3
  flutter_spinkit: ^5.2.1
  fixnum: ^1.1.1
  platform_detector: ^0.2.0
  mobile_scanner: ^6.0.2
  flutter_webrtc: ^0.12.3
  fido2: ^0.0.4
  ccid: ^0.1.7
  device_info_plus: ^11.2.0
  file_saver: ^0.2.14
  basic_utils:
    git:
      url: https://github.com/dangfan/Dart-Basic-Utils.git
      ref: 743c57a717a8425f9baf3f363f9359216dcb832e
  rust_lib_canokey_console:
    path: rust_builder
  flutter_rust_bridge: 2.7.0
  logger: ^2.5.0

dependency_overrides:
  dart_webrtc: ^1.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/

flutter_intl:
  enabled: true
